// Generated by CoffeeScript 1.7.1
(function() {
  var TRM, diff_match_patch, green, red, white;

  diff_match_patch = require('googlediff');

  TRM = require('coffeenode-trm');

  red = TRM.RED.bind(TRM);

  white = TRM.white.bind(TRM);

  green = TRM.GREEN.bind(TRM);

  this._new_diff = function(text1, text2) {
    var R, d, dmp;
    dmp = new diff_match_patch();
    d = dmp.diff_main(text1, text2);
    R = {
      dmp: dmp,
      d: d
    };
    return R;
  };

  this._cleanup = function(me) {
    var d, dmp;
    d = me.d, dmp = me.dmp;
    dmp.Diff_EditCost = 10;
    dmp.diff_cleanupSemantic(d);
    dmp.diff_cleanupEfficiency(d);
    return me;
  };

  this.analyze = function(text1, text2) {
    var d, dmp, _ref;
    _ref = this._cleanup(this._new_diff(text1, text2)), d = _ref.d, dmp = _ref.dmp;
    return d;
  };

  this.colorize = function(text1, text2) {
    var R, action, part, text, _i, _len, _ref;
    R = [];
    _ref = this.analyze(text1, text2);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      part = _ref[_i];
      action = part[0], text = part[1];
      R.push((this._get_color(action))(text));
    }
    return R.join('');
  };

  this._get_color = function(action) {
    if (action === -1) {
      return red;
    }
    if (action === 0) {
      return white;
    }
    if (action === +1) {
      return green;
    }
  };

}).call(this);
