// Generated by CoffeeScript 1.10.0
(function() {
  var CND, diff_match_patch, green, red, white;

  diff_match_patch = require('googlediff');

  CND = require('cnd');

  red = CND.red.bind(CND);

  white = CND.white.bind(CND);

  green = CND.green.bind(CND);

  this._new_diff = function(text1, text2) {
    var R, d, dmp;
    dmp = new diff_match_patch();
    d = dmp.diff_main(text1, text2);
    R = {
      dmp: dmp,
      d: d
    };
    return R;
  };

  this._cleanup = function(me) {
    var d, dmp;
    d = me.d, dmp = me.dmp;
    dmp.Diff_EditCost = 10;
    dmp.diff_cleanupSemantic(d);
    dmp.diff_cleanupEfficiency(d);
    return me;
  };

  this.analyze = function(text1, text2) {
    var d, dmp, ref;
    ref = this._cleanup(this._new_diff(text1, text2)), d = ref.d, dmp = ref.dmp;
    return d;
  };

  this.colorize = function(text1, text2) {
    var R, action, i, len, part, ref, text;
    R = [];
    ref = this.analyze(text1, text2);
    for (i = 0, len = ref.length; i < len; i++) {
      part = ref[i];
      action = part[0], text = part[1];
      R.push((this._get_color(action))(text));
    }
    return R.join('');
  };

  this._get_color = function(action) {
    if (action === -1) {
      return red;
    }
    if (action === 0) {
      return white;
    }
    if (action === +1) {
      return green;
    }
  };

}).call(this);
